# The URL the site will be built for
base_url = "https://akbarpn136.github.io/tutorial/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# The theme to use for code highlighting.
highlight_theme = "base16-ocean-dark"

# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[extra]
# Put all your custom variables here
judul = "Koleksi Tutorial"
author = "4KB4RPN136"