name: Koleksi Tutorial

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

  build_website:
    name: Build Website with Zola Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout using action
        uses: actions/checkout@master
      - name: Build and deploy using action
        uses: shalzz/zola-deploy-action@v0.12.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.WORKFLOW_TOKEN }}